apiVersion: apps/v1
kind: Deployment
metadata:
  name: tp6billingapp-deployment
spec:
  selector:
    matchLabels:
      app: tp6billingapp
  replicas: 3
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: tp6billingapp
    spec:
      containers:
      - name: tp6billingapp
        image: lucaseveron/tp6billingapp:v1
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "256Mi"
            cpu: "200m"
          requests:
            memory: "128Mi"
            cpu: "100m"
        volumeMounts:
        - name: data-volume
          mountPath: /app/data
      volumes:
      - name: data-volume
        emptyDir: {}

---

apiVersion: v1
kind: Service
metadata:
  name: tp6billingapp-service
spec:
  selector:
    app: tp6billingapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort

---

apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: tp6billingapp-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: tp6billingapp-deployment
  minReplicas: 3
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50


       
