apiVersion: apps/v1
kind: Deployment
metadata:
  name: lucaseveron-tp6billin
  labels:
    app: appjava
spec:
  replicas: 3
  selector:
    matchLabels:
      app: appjava
  template:
    metadata:
     name: lucaseveron-tp6billin-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: lucaseveron-tp6billin
  minReplicas: 3
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
      labels:
        app: appjava
    spec:
      containers:
        - name: appjava
          image: lucaseveron/tp6billingapp:v1
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 7080
          volumeMounts:
            - name: logs
              mountPath: /var/logs
      volumes:
        - name: logs
          emptyDir: {}
          

 
    
      

